name: themes-weekly-pull

on:
  schedule:
    # run every friday at 5AM
    - cron: '0 5 * * 5'
  workflow_dispatch:

env:
  NODE_VERSION: 14.x

jobs:
  pull-from-jsonbin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Run themes:pull script
        run: yarn run themes:pull
        env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}
          BIN_ID: ${{ secrets.BIN_ID }}

      - name: Generate dark tokens
        run: npx token-transformer scripts/themes/tokens/arduino-tokens.json scripts/themes/tokens/dark.json core,ide-default,ide-dark,theia core,ide-default,ide-dark

      - name: Generate default tokens
        run: npx token-transformer scripts/themes/tokens/arduino-tokens.json scripts/themes/tokens/default.json core,ide-default,theia core,ide-default

      - name: Run themes:generate script
        run: yarn run themes:generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Updated themes
          title: Update themes
          branch: themes/themes-update
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: ${{ github.head_ref }}
